export const APP_REQUEST = 'APP_REQUEST'
export const APP_SUCCESS = 'APP_SUCCESS'
export const APP_FAIL = 'APP_FAIL'
export const APP_ON_LOGIN_MODAL = 'APP_ON_LOGIN_MODAL'
export const APP_OFF_LOGIN_MODAL = 'APP_OFF_LOGIN_MODAL'


